x-php-common: &php-common
  restart: always
  volumes:
    # PHP configuration files
    - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
    # Web projects
    - "./projects:/var/www/projects"
    # Logs
    - "./logs/php:/var/log/php"
    # Sessions and temp files
    - php_sessions:/tmp/sessions
    - php_uploads:/tmp/uploads
  networks:
    - webstack
  environment:
    - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/usr/local/etc/php/custom.d
    - PHP_FPM_LISTEN=9000
    # Memory & Performance
    - PHP_MEMORY_LIMIT=512M
    - PHP_MAX_EXECUTION_TIME=300
    - PHP_POST_MAX_SIZE=100M
    - PHP_UPLOAD_MAX_FILESIZE=100M
    - PHP_MAX_INPUT_VARS=3000
    - PHP_MAX_INPUT_TIME=300
    # OPcache optimizations
    - PHP_OPCACHE_ENABLE=1
    - PHP_OPCACHE_MEMORY_CONSUMPTION=256
    - PHP_OPCACHE_MAX_ACCELERATED_FILES=20000
    - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
    - PHP_OPCACHE_REVALIDATE_FREQ=0
    - PHP_OPCACHE_SAVE_COMMENTS=0
    # Security & Error handling
    - PHP_EXPOSE_PHP=0
    - PHP_DISPLAY_ERRORS=0
    - PHP_LOG_ERRORS=1
    # Session optimizations
    - PHP_SESSION_SAVE_HANDLER=files
    - PHP_SESSION_SAVE_PATH=/tmp/sessions
    - PHP_SESSION_GC_MAXLIFETIME=7200
    # Timezone configuration
    - TZ=${TIMEZONE:-Asia/Kuala_Lumpur}
  healthcheck:
    test: ["CMD", "php", "-v"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 60s
  deploy:
    resources:
      limits:
        memory: 1G
        cpus: "1.0"
      reservations:
        memory: 256M
        cpus: "0.25"

services:
  # Database Service - Master
  database:
    image: mariadb:latest
    container_name: "webstack-mariadb-master"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./db/mariadb:/var/lib/mysql"
      - "./etc/mariadb:/etc/mysql/conf.d"
      - "./logs/mariadb:/var/log/mysql"
      - mariadb_temp:/tmp
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-12345}
      MYSQL_DATABASE: ${DB_NAME:-webstack}
      MYSQL_USER: ${DB_USER:-webstack}
      MYSQL_PASSWORD: ${DB_PASSWORD:-webstack}
      MARIADB_AUTO_UPGRADE: 1
      # Replication configuration
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: ${DB_REPLICATION_USER:-replicator}
      MYSQL_REPLICATION_PASSWORD: ${DB_REPLICATION_PASSWORD:-repl123}
      # Timezone configuration
      TZ: ${TIMEZONE:-Asia/Kuala_Lumpur}
      # Performance optimizations
      MYSQL_INNODB_BUFFER_POOL_SIZE: ${DB_INNODB_BUFFER_POOL_SIZE:-512M}
      MYSQL_INNODB_LOG_FILE_SIZE: ${DB_INNODB_LOG_FILE_SIZE:-128M}
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: ${DB_INNODB_FLUSH_LOG_AT_TRX_COMMIT:-2}
      MYSQL_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS:-200}
      MYSQL_QUERY_CACHE_SIZE: ${DB_QUERY_CACHE_SIZE:-128M}
      MYSQL_QUERY_CACHE_TYPE: ${DB_QUERY_CACHE_TYPE:-1}
      MYSQL_THREAD_CACHE_SIZE: ${DB_THREAD_CACHE_SIZE:-16}
      MYSQL_TABLE_OPEN_CACHE: ${DB_TABLE_OPEN_CACHE:-2000}
      MYSQL_SORT_BUFFER_SIZE: ${DB_SORT_BUFFER_SIZE:-2M}
      MYSQL_READ_BUFFER_SIZE: ${DB_READ_BUFFER_SIZE:-128K}
      MYSQL_READ_RND_BUFFER_SIZE: ${DB_READ_RND_BUFFER_SIZE:-256K}
      MYSQL_KEY_BUFFER_SIZE: ${DB_KEY_BUFFER_SIZE:-128M}
    networks:
      - webstack
    healthcheck:
      test:
        [
          "CMD",
          "mariadb",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD:-12345}",
          "-e",
          "SELECT 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 512M
          cpus: "0.5"
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --innodb-buffer-pool-size=${DB_INNODB_BUFFER_POOL_SIZE:-512M}
      --innodb-log-file-size=${DB_INNODB_LOG_FILE_SIZE:-128M}
      --innodb-flush-log-at-trx-commit=${DB_INNODB_FLUSH_LOG_AT_TRX_COMMIT:-2}
      --max-connections=${DB_MAX_CONNECTIONS:-200}
      --query-cache-size=${DB_QUERY_CACHE_SIZE:-128M}
      --query-cache-type=${DB_QUERY_CACHE_TYPE:-1}
      --thread-cache-size=${DB_THREAD_CACHE_SIZE:-16}
      --table-open-cache=${DB_TABLE_OPEN_CACHE:-2000}
      --sort-buffer-size=${DB_SORT_BUFFER_SIZE:-2M}
      --read-buffer-size=${DB_READ_BUFFER_SIZE:-128K}
      --read-rnd-buffer-size=${DB_READ_RND_BUFFER_SIZE:-256K}
      --key-buffer-size=${DB_KEY_BUFFER_SIZE:-128M}
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2

  # Database Service - Slave (Read Replica)
  database-slave:
    image: mariadb:latest
    container_name: "webstack-mariadb-slave"
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - "./db/mariadb-slave:/var/lib/mysql"
      - "./etc/mariadb-slave:/etc/mysql/conf.d"
      - "./logs/mariadb-slave:/var/log/mysql"
      - mariadb_slave_temp:/tmp
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-12345}
      MYSQL_DATABASE: ${DB_NAME:-webstack}
      MYSQL_USER: ${DB_USER:-webstack}
      MYSQL_PASSWORD: ${DB_PASSWORD:-webstack123}
      MARIADB_AUTO_UPGRADE: 1
      # Timezone configuration
      TZ: ${TIMEZONE:-Asia/Kuala_Lumpur}
      # Performance optimizations (reduced for slave)
      MYSQL_INNODB_BUFFER_POOL_SIZE: ${DB_SLAVE_INNODB_BUFFER_POOL_SIZE:-256M}
      MYSQL_INNODB_LOG_FILE_SIZE: ${DB_INNODB_LOG_FILE_SIZE:-128M}
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: ${DB_INNODB_FLUSH_LOG_AT_TRX_COMMIT:-2}
      MYSQL_MAX_CONNECTIONS: ${DB_SLAVE_MAX_CONNECTIONS:-100}
      MYSQL_QUERY_CACHE_SIZE: ${DB_QUERY_CACHE_SIZE:-128M}
      MYSQL_QUERY_CACHE_TYPE: ${DB_QUERY_CACHE_TYPE:-1}
      MYSQL_THREAD_CACHE_SIZE: ${DB_THREAD_CACHE_SIZE:-16}
      MYSQL_TABLE_OPEN_CACHE: ${DB_TABLE_OPEN_CACHE:-2000}
      MYSQL_SORT_BUFFER_SIZE: ${DB_SORT_BUFFER_SIZE:-2M}
      MYSQL_READ_BUFFER_SIZE: ${DB_READ_BUFFER_SIZE:-128K}
      MYSQL_READ_RND_BUFFER_SIZE: ${DB_READ_RND_BUFFER_SIZE:-256K}
      MYSQL_KEY_BUFFER_SIZE: ${DB_KEY_BUFFER_SIZE:-128M}
    networks:
      - webstack
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "mariadb",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD:-12345}",
          "-e",
          "SELECT 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.25"
    command: >
      --server-id=2
      --relay-log=mysql-relay-bin
      --log-bin=mysql-bin
      --binlog-format=ROW
      --read-only=1
      --skip-slave-start=0
      --innodb-buffer-pool-size=${DB_SLAVE_INNODB_BUFFER_POOL_SIZE:-256M}
      --innodb-log-file-size=${DB_INNODB_LOG_FILE_SIZE:-128M}
      --innodb-flush-log-at-trx-commit=${DB_INNODB_FLUSH_LOG_AT_TRX_COMMIT:-2}
      --max-connections=${DB_SLAVE_MAX_CONNECTIONS:-100}
      --query-cache-size=${DB_QUERY_CACHE_SIZE:-128M}
      --query-cache-type=${DB_QUERY_CACHE_TYPE:-1}
      --thread-cache-size=${DB_THREAD_CACHE_SIZE:-16}
      --table-open-cache=${DB_TABLE_OPEN_CACHE:-2000}
      --sort-buffer-size=${DB_SORT_BUFFER_SIZE:-2M}
      --read-buffer-size=${DB_READ_BUFFER_SIZE:-128K}
      --read-rnd-buffer-size=${DB_READ_RND_BUFFER_SIZE:-256K}
      --key-buffer-size=${DB_KEY_BUFFER_SIZE:-128M}
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2

  # Web Server Service
  webserver:
    build: ./nginx-stack
    container_name: "webstack-nginx"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    restart: always
    volumes:
      # Nginx configuration files
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro"
      - "./etc/nginx/mime.types:/etc/nginx/mime.types:ro"
      # SSL certificates
      - "./etc/ssl:/etc/ssl/private:ro"
      # Web projects and static files (includes project-specific nginx.conf)
      - "./projects:/var/www/projects:ro"
      # Logs
      - "./logs/nginx:/var/log/nginx"
      # Cache and temp directories
      - nginx_cache:/var/cache/nginx
      - nginx_temp:/tmp/nginx
      - nginx_body_temp:/var/cache/nginx/client_temp
      - nginx_proxy_temp:/var/cache/nginx/proxy_temp
      - nginx_fastcgi_temp:/var/cache/nginx/fastcgi_temp
    depends_on:
      database:
        condition: service_healthy
      php56:
        condition: service_healthy
      php70:
        condition: service_healthy
      php71:
        condition: service_healthy
      php72:
        condition: service_healthy
      php73:
        condition: service_healthy
      php74:
        condition: service_healthy
      php80:
        condition: service_healthy
      php81:
        condition: service_healthy
      php82:
        condition: service_healthy
      php83:
        condition: service_healthy
      php84:
        condition: service_healthy
    networks:
      - webstack
    environment:
      # Timezone configuration
      - TZ=${TIMEZONE:-Asia/Kuala_Lumpur}
      # Performance optimizations
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=2048
      - NGINX_WORKER_RLIMIT_NOFILE=4096
      - NGINX_KEEPALIVE_TIMEOUT=65
      - NGINX_KEEPALIVE_REQUESTS=1000
      - NGINX_CLIENT_MAX_BODY_SIZE=100M
      - NGINX_CLIENT_BODY_BUFFER_SIZE=128k
      - NGINX_CLIENT_HEADER_BUFFER_SIZE=1k
      - NGINX_LARGE_CLIENT_HEADER_BUFFERS=4 4k
      # Gzip optimizations
      - NGINX_GZIP=on
      - NGINX_GZIP_COMP_LEVEL=6
      - NGINX_GZIP_MIN_LENGTH=1000
      - NGINX_GZIP_VARY=on
      # Rate limiting
      - NGINX_LIMIT_REQ_ZONE=$$binary_remote_addr zone=api:10m rate=10r/s
      - NGINX_LIMIT_CONN_ZONE=$$binary_remote_addr zone=addr:10m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 128M
          cpus: "0.25"

  # PHP 5.6 Service
  php56:
    <<: *php-common
    build:
      context: ./php-stack-5.6.30-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php56"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/5.6:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/5.6/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php56:/var/log/php"
      # Sessions and temp files
      - php56_sessions:/tmp/sessions
      - php56_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=5.6

  # PHP 7.0 Service
  php70:
    <<: *php-common
    build:
      context: ./php-stack-7.0-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php70"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/7.0:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/7.0/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php70:/var/log/php"
      # Sessions and temp files
      - php70_sessions:/tmp/sessions
      - php70_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=7.0

  # PHP 7.1 Service
  php71:
    <<: *php-common
    build:
      context: ./php-stack-7.1-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php71"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/7.1:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/7.1/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php71:/var/log/php"
      # Sessions and temp files
      - php71_sessions:/tmp/sessions
      - php71_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=7.1

  # PHP 7.2 Service
  php72:
    <<: *php-common
    build:
      context: ./php-stack-7.2-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php72"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/7.2:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/7.2/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php72:/var/log/php"
      # Sessions and temp files
      - php72_sessions:/tmp/sessions
      - php72_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=7.2

  # PHP 7.3 Service
  php73:
    <<: *php-common
    build:
      context: ./php-stack-7.3-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php73"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/7.3:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/7.3/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php73:/var/log/php"
      # Sessions and temp files
      - php73_sessions:/tmp/sessions
      - php73_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=7.3

  # PHP 7.4 Service
  php74:
    <<: *php-common
    build:
      context: ./php-stack-7.4-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php74"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/7.4:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/7.4/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php74:/var/log/php"
      # Sessions and temp files
      - php74_sessions:/tmp/sessions
      - php74_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=7.4

  # PHP 8.0 Service
  php80:
    <<: *php-common
    build:
      context: ./php-stack-8.0-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php80"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/8.0:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/8.0/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php80:/var/log/php"
      # Sessions and temp files
      - php80_sessions:/tmp/sessions
      - php80_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=8.0

  # PHP 8.1 Service
  php81:
    <<: *php-common
    build:
      context: ./php-stack-8.1-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php81"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/8.1:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/8.1/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php81:/var/log/php"
      # Sessions and temp files
      - php81_sessions:/tmp/sessions
      - php81_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=8.1

  # PHP 8.2 Service
  php82:
    <<: *php-common
    build:
      context: ./php-stack-8.2-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php82"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/8.2:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/8.2/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php82:/var/log/php"
      # Sessions and temp files
      - php82_sessions:/tmp/sessions
      - php82_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=8.2

  # PHP 8.3 Service
  php83:
    <<: *php-common
    build:
      context: ./php-stack-8.3-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php83"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/8.3:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/8.3/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php83:/var/log/php"
      # Sessions and temp files
      - php83_sessions:/tmp/sessions
      - php83_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=8.3

  # PHP 8.4 Service
  php84:
    <<: *php-common
    build:
      context: ./php-stack-8.4-fpm
      dockerfile: Dockerfile
    container_name: "webstack-php84"
    volumes:
      # PHP configuration files
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/00-general.ini:ro"
      - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./etc/php/8.4:/usr/local/etc/php/conf.d/99-version:ro"
      - "./etc/php/8.4/php-fpm.d:/usr/local/etc/php-fpm.d:ro"
      # Web projects
      - "./projects:/var/www/projects"
      # Logs
      - "./logs/php84:/var/log/php"
      # Sessions and temp files
      - php84_sessions:/tmp/sessions
      - php84_uploads:/tmp/uploads
    environment:
      - PHP_VERSION=8.4

  # Redis Service (optional)
  cache:
    image: redis:alpine
    container_name: "webstack-redis"
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - "./db/redis:/data"
      - "./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
      - TZ=${TIMEZONE:-Asia/Kuala_Lumpur}
    networks:
      - webstack
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  webstack:
    driver: bridge
    name: webstack-network

volumes:
  database_data:
  cache_data:
  mariadb_temp:
  mariadb_slave_temp:
  nginx_cache:
  nginx_temp:
  nginx_body_temp:
  nginx_proxy_temp:
  nginx_fastcgi_temp:
  php_sessions:
  php_uploads:
  php56_sessions:
  php56_uploads:
  php70_sessions:
  php70_uploads:
  php71_sessions:
  php71_uploads:
  php72_sessions:
  php72_uploads:
  php73_sessions:
  php73_uploads:
  php74_sessions:
  php74_uploads:
  php80_sessions:
  php80_uploads:
  php81_sessions:
  php81_uploads:
  php82_sessions:
  php82_uploads:
  php83_sessions:
  php83_uploads:
  php84_sessions:
  php84_uploads:
