# Docker Compose Override for Development
# This file is automatically loaded and can be used to override
# settings for local development

services:
  # Development overrides for webserver
  webserver:
    environment:
      # Disable rate limiting in development
      - NGINX_LIMIT_REQ_ZONE=off
      - NGINX_LIMIT_CONN_ZONE=off

  # Development overrides for database
  database:
    environment:
      # Enable general query log in development
      - MYSQL_GENERAL_LOG=1
      - MYSQL_GENERAL_LOG_FILE=/var/log/mariadb/general.log

  # Development overrides for cache
  cache:
    ports:
      # Expose Redis to all interfaces in development
      - "6379:6379"

  # Development overrides for PHP services (example for php84)
  # php84:
  #   environment:
  #     # Enable error display in development
  #     - PHP_DISPLAY_ERRORS=1
  #     - PHP_DISPLAY_STARTUP_ERRORS=1
  #     - PHP_ERROR_REPORTING=E_ALL
  #     # Enable OPcache validation in development
  #     - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
  #     - PHP_OPCACHE_REVALIDATE_FREQ=2
  #   volumes:
  #     # Add development tools
  #     - "./dev-tools:/var/www/dev-tools:ro"

  # Add Redis commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: "webstack-redis-commander"
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: "local:cache:6379"
    networks:
      - webstack
    depends_on:
      - cache
