version: '3.7'
services:
    mariadb:
        image: mariadb
        container_name: "mariadb"
        ports:
            # only allow port 3306 access from localhost only
            - "127.0.0.1:3306:3306"
        volumes:
            - "./db/mariadb:/var/lib/mysql:rw"
            - "./etc/mysql/:/etc/mysql/"
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            # - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
            - "MYSQL_ROOT_PASSWORD=12345"
            - "SET GLOBAL sql_mode =''"
        networks:
            - docker_webstack
    nginx:
        image: nginx:latest
        container_name: "nginx"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./projects/:/var/www/projects"
        depends_on:
            - php7
            - php5
            - mariadb
        networks:
            - docker_webstack
    php7:
        build: php-stack-7-fpm
        container_name: "php7"
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./projects/:/var/www/projects"
        networks:
            - docker_webstack
    php5:
        build: php-stack-5.6.30-fpm
        container_name: "php5"
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./projects/:/var/www/projects"
        networks:
            - docker_webstack
networks:
    docker_webstack:
        driver: bridge
